---
- hosts: AppServer
  vars_files: 
    - variables.yml
 
  tasks:
    - name: install all the required packages
      sudo: yes
      apt: name={{item}}
      with_items:
        - tomcat6
        - curl
        - subversion
        - git
        - vim
        - openjdk-6-jdk
        #- libicu48
        - build-essential 
        - zlib1g-dev 
        - libssl-dev 
        - libreadline6-dev 
        - libyaml-dev
    
    - include: svn.yml
    - include: phantom_js.yml
    - include: java.yml